install! 'cocoapods', :warn_for_unused_master_specs_repo => false

platform :ios, "13.0"
inhibit_all_warnings!

def pods
  #swift
  pod 'RxSwift' #线程
  pod 'SnapKit' #适配
  pod 'Alamofire' #网络基础库
  pod 'SwiftyJSON' #json解析
  pod 'Kingfisher' #图片加载
  pod 'SwiftyUserDefaults' #NSUserdefaults
  pod 'SQLite.swift' #数据库
  pod 'ReachabilitySwift' #网络状况监测
  pod 'HXPHPicker' #相册图片选择
  pod 'SkeletonView' #骨架（待验证使用）
  pod 'GKPageScrollViewSwift' #分类切换
  
  #oc
  pod 'MJRefresh' #刷新
  pod 'AlipaySDK-iOS' #支付宝支付
  pod 'WechatOpenSDK' #微信支付
  pod 'SVProgressHUD' #提示框
end

target 'YXSwiftBasicProj' do
    pods

post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
   end
  end
end

end
